"""add visit ID to delay schema

Revision ID: 120a81d34a73
Revises: d62a0cb51304
Create Date: 2020-09-24 17:06:21.329020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120a81d34a73'
down_revision = 'd62a0cb51304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_delay_visit_id_visit'), 'visit', ['visit_id'], ['id'])

    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_trip_id'), ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_trip_id'), type_='unique')

    with op.batch_alter_table('delay', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_delay_visit_id_visit'), type_='foreignkey')
        batch_op.drop_column('visit_id')

    # ### end Alembic commands ###
