"""initial tables

Revision ID: 6ee75fcef319
Revises: 
Create Date: 2020-09-19 18:33:10.868919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee75fcef319'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('route_id', sa.String(length=30), nullable=True),
    sa.Column('line_id', sa.String(length=2), nullable=True),
    sa.Column('has_started', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('has_finished', sa.Boolean(), nullable=True),
    sa.Column('has_predictions', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('delay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('trip_id', sa.String(length=30), nullable=True),
    sa.Column('route_id', sa.String(length=30), nullable=True),
    sa.Column('station_id', sa.String(length=8), nullable=True),
    sa.Column('station_name', sa.String(length=40), nullable=True),
    sa.Column('line_id', sa.String(length=2), nullable=True),
    sa.Column('delay_amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delay', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delay_timestamp'), ['timestamp'], unique=False)

    op.create_table('station_line_pair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(length=8), nullable=True),
    sa.Column('line_id', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.String(length=30), nullable=True),
    sa.Column('station_id', sa.String(length=8), nullable=True),
    sa.Column('station_name', sa.String(length=40), nullable=True),
    sa.Column('line_id', sa.String(length=2), nullable=True),
    sa.Column('direction', sa.String(length=1), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('pred_arrival_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit')
    op.drop_table('station_line_pair')
    with op.batch_alter_table('delay', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delay_timestamp'))

    op.drop_table('delay')
    op.drop_table('trip')
    op.drop_table('station')
    # ### end Alembic commands ###
