"""added route_id to visit schema

Revision ID: d62a0cb51304
Revises: 6ee75fcef319
Create Date: 2020-09-23 18:18:36.190694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62a0cb51304'
down_revision = '6ee75fcef319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_id', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.drop_column('route_id')

    # ### end Alembic commands ###
